services:

  web:
    image: 04-webserver-demo:1.0
    container_name: python-webserver
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
    - ./webserver/web_root:/app # <--- This is a relative path. So it depends where you start the image
    - time_file:/app/time
    depends_on:
      - time-fetcher
    

  time-fetcher:
    build: python-timefetcher
    volumes:
    - time_file:/time/time_file

volumes:
  time_file: 
