FROM debian:12-slim

WORKDIR /workdir
SHELL ["/bin/bash", "-c"]
RUN apt update
RUN apt install -y curl build-essential
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

ENV PATH=${PATH}:/root/.cargo/bin
RUN rustup target add armv7-unknown-linux-gnueabihf
RUN apt install -y gcc-arm-linux-gnueabihf
CMD [ "cargo", "build" ]
