FROM debian:13-slim

WORKDIR /workdir
SHELL ["/bin/bash", "-c"]
RUN apt update
RUN apt install -y curl build-essential
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

ENV PATH=${PATH}:/root/.cargo/bin

CMD [ "/bin/bash", "-c" , "cargo build"]


